### PR TITLE
simplify odf meta parsing

### PR DESCRIPTION
**Pull request by andiwand**
#67

### CODE REVIEW

**Comment by TomTasche** [comment]
Found a few other cases where you could have used recursiveVisitElementsWithName while reviewing the other pull request. I thought that's on purpose to be more explicit and failsafe. Will leave a comment next time I spot something like that!

**Comment by andiwand** [comment]
> Found a few other cases where you could have used recursiveVisitElementsWithName while reviewing the other pull request. I thought that's on purpose to be more explicit and failsafe. Will leave a comment next time I spot something like that!

recursive is actually not perfect because we travel much deeper then we need to. but it does its job. i think it would be best to use xpath.

**Comment by TomTasche** [comment]
> > Found a few other cases where you could have used recursiveVisitElementsWithName while reviewing the other pull request. I thought that's on purpose to be more explicit and failsafe. Will leave a comment next time I spot something like that!
> 
> recursive is actually not perfect because we travel much deeper then we need to. but it does its job. i think it would be best to use xpath.

Haha exactly my thoughts! Saw that XPath would require another library and thought nevermind...

**Comment by andiwand** [comment]
> > > Found a few other cases where you could have used recursiveVisitElementsWithName while reviewing the other pull request. I thought that's on purpose to be more explicit and failsafe. Will leave a comment next time I spot something like that!
> > 
> > 
> > recursive is actually not perfect because we travel much deeper then we need to. but it does its job. i think it would be best to use xpath.
> 
> Haha exactly my thoughts! Saw that XPath would require another library and thought nevermind...

i think it would be worth it but depending on when we switch to javascript. i guess there it is built-in.

**Comment by andiwand** [comment]
https://github.com/andiwand/OpenDocument.core/issues/69

**Pull request merged**
